services:
  app:
    ports: !override
      - "127.0.0.1:${CHATGPT2API_PORT:-8000}:80"
    networks:
      default:
      sub2api:
        aliases:
          - gptgrok2api

networks:
  sub2api:
    external: true
    name: deploy_sub2api-network
